# Used in GitHub CI.
# Don't use this config to run the service in production.

version: '3'
volumes:
  database: {}
services:
  db:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres:12.2
    volumes:
      - database:/var/lib/postgresql/data
  app:
    environment:
      - SECRET_KEY_BASE=abd834a091ca2069a660b50dd50cffa0b9d5f6bd51395da186f07785c14f14bb52109b4d8bb3344cb8eb31ada9dd2a10a3422ef73317c0923ee32a732557faac
      - DB_TEST_DATABASE=texterify_test_node_api
      - RAILS_ENV=test
      - PROPRIETARY_MODE=true
    image: chrztoph/texterify:test
    depends_on:
      - db
    ports:
      - '3300:3000'
