name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['10.x', '12.x', '14.x']
        os: [ubuntu-18.04]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Run docker-compose
        run: docker-compose -f docker-compose.yml -f docker-compose.github.yml up -d

      - name: Create and seed test database
        run: docker-compose exec -T app bundle exec rails db:create db:migrate db:seed RAILS_ENV=test

      - name: Install test dependencies
        run: docker-compose exec -T app bundle install --with test

      - name: Restart containers
        run: docker-compose restart

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build
